package:
  name: rif
  version: {{ GIT_DESCRIBE_TAG }}
source:
  number: {{ GIT_DESCRIBE_NUMBER }}
  git_url: ../.

build:
  script: pip install parsimonious && python setup.py install

test:
  requires:
    - pytest
  commands:
    - pytest --pyargs rif.hash

requirements:
  build:
    - python {{ python }}
    - numpy
    - jinja2
    - six
    - boost
  run:
    - python
    - numpy
    - pandas
    - six
