package:
  name: rif
  version: {{ GIT_DESCRIBE_TAG }}
source:
  git_url: ../.

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: pip install parsimonious && python setup.py install

test:
  requires:
    - pytest
  commands:
    - pytest --pyargs rif

requirements:
  build:
    - python {{ python }}
    - jinja2
    - six
    - numpy=1.13.1
    - boost
    - ninja
  run:
    - python
    - numpy=1.13.1
    - pandas
    - six
