package:
  name: rif
  version: 0.1.0
source:
  path: ../.

build:
  script: pip install parsimonious && python setup.py install

requirements:
  build:
    - python
    - numpy
    - jinja2
    - boost
  run:
    - python
    - numpy
    - pandas
