package:
  name: rif
  version: 0.1.0
source:
  path: ../.

build:
  script: pip install parsimonious && python setup.py install

test:
  requires:
    - pytest
    - pytest-xdist
  commands:
    - pytest -v -n4 --pyargs rif

requirements:
  build:
    - python >=3.6
    - numpy
    - jinja2
    - six
    - boost
    - ninja
  run:
    - python >=3.6
    - numpy
    - pandas
    - six
