name: build_rif
dependencies:
 - python
 - numpy
 - pandas

#  - scipy
#  - PyYAML
#  - colorama
#  - future
#  - jinja2
#  - pandas
#  - xarray
#  - pytest
#  - pytest-cov
#  - sphinx_rtd_theme
#  - mock
#  - seaborn
#  - dask
#  - pip
#    - pytest-cpp
#    - breathe
#    - hypothesis
#    - pytest-sugar
#    - pytest-xdist
#    - sphinxcontrib-napoleon
#    - tqdm
#    - homog
#    - pytest-runner
